### ISSUE TITLE
Photomode無法切換角色

### ISSUE THREAD

**Issue by anyukari** [alex94539/ShinyColorsDB-SpineViewer#3]
Uncaught ReferenceError: ClearDragStatus is not defined
    at HTMLSelectElement.SetupIdolList.idolList.onchange (main.js:264)
有個方法未被定義

**Comment by alex94539** [comment]
[a05773a70220c2e471afbcaa07545f5b1de5b959](https://github.com/alex94539/ShinyColorsDB-SpineViewer/commit/a05773a70220c2e471afbcaa07545f5b1de5b959)
清除dead code
photomode這邊之後應該會以pixijs重寫，最慢明年二月
可撥考研仔:(((
